### ISSUE TITLE
expose default reporting

### ISSUE THREAD

**Issue by FND** [doesdev/rollup-plugin-analyzer#2]
Currently we have to decide between custom reporting via `onAnalysis` and rollup-plugin-analyzer's own (elaborate and useful) default reporting: Supplying the former disables the latter.

It would be helpful if the two weren't mutually exclusive so we could [emit a summary](https://github.com/faucet-pipeline/faucet-pipeline-js/blob/68c8107dc9ec6a0b6b11f01792d6ef781cabf940/lib/index.js#L42-L45) while optionally _also_ emitting the [full report](https://github.com/doesdev/rollup-plugin-analyzer/blob/77ed7650e1140cf8bba89722b304ca00a0c7c804/module.js#L69-L104).

I imagine it might look something like this:

```javascript
import { plugin as analyze, report } from 'rollup-plugin-analyzer'
…
    plugins: [analyze({onAnalysis})]
…
function onAnalysis(params) {
    console.error(`${params.bundleOrigSize} →  ${params.bundleSize}`)

    if (FULL_REPORT) {
        console.error(report(params))
    }
}
```

**Comment by doesdev** [comment]
So, I've done a couple things in this commit (will go out as 2.1.0 later). First I changed the behavior of `onAnalysis` so that it by default does not suppress the formatted output. In order to suppress it an option has been added `skipFormatted`. I think that's probably the cleanest solution and how `onAnalysis` should have been initially implemented.

I did also export the reporter as `reporter`, but I didn't document it as it's just an uglier way of accomplishing the same so I can't recommend it. The only case I could see it being useful is manipulating the analysis before sending it to the reporter, but can't think of any good reason to do that. Anyway, if you were to use it you would to call it with the `analysisObject` returned from `onAnalysis` as the first argument and the original options object as the second.
