### ISSUE TITLE
Feature request: only show the header (global summary)

### ISSUE THREAD

**Issue by incorrupt** [doesdev/rollup-plugin-analyzer#23]
If set to true, this would only show the "header":

```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    68.771 KB
original size:  123.56 KB
code reduction: 44.34 %
module count:   79
```

Also, there is some confusion around the usage of "summary" which means "file details summary" in some cases (`summaryOnly`) and "header" in some other cases (`filterSummary`)

I suggest one of these solutions:
- **deprecate `filterSummary` to be replaced by `filterHeader` (and my feature request could be something like `headerOnly`)**
- deprecate `summaryOnly` to be replaced by `fileSummaryOnly` (and my feature request could be something like `globalSummaryOnly`)

**Comment by incorrupt** [comment]
Current alternative solution is to filter out everything
```
plugins: [
    analyze({ filter: (m) => false }),
  ]
```

**Comment by doesdev** [comment]
Thanks for the feedback, I'm glad to see you're getting use out of the module. That being said, based on the other feedback you've provided I'm thinking that you may be looking for something a bit different than what this module intends to provide, and there are other modules out there that do provide exactly what you're looking for. I mentioned [rollup-plugin-size-snapshot](https://github.com/TrySound/rollup-plugin-size-snapshot) in another issue and I do think that might be a good fit for what you're trying to accomplish.

That said, I'm not opposed to a header only option. However, I just want to be clear about the intent of this module which is mostly concerned with providing details about individual modules that make up the bundle, allowing developers to drill down to what has the most impact, in relative terms, to the overall bundle size.

I am going to close this since I do think other modules might be a better fit, but if you check out the alternatives and feel like this is still the best fit but would work even better with a headerOnly option feel free to drop back in and comment / re-open.

**Comment by incorrupt** [comment]
Indeed for my use case, that other plugin is more appropriate. Thanks for pointing it out 👍
