### ISSUE TITLE
New release with html reports?

### ISSUE THREAD

**Issue by jharris4** [doesdev/rollup-plugin-analyzer#8]
Hi, thanks for your work on this plugin!

I was just trying it out with the hope of using the new `htmlReportPath` option and was scratching my head wondering why it's not working, until I realized it hasn't been released yet!

Is there anything specific that's holding things up for a new release with the html reports?

**Comment by doesdev** [comment]
I was hoping to release soon after Rollup 1.0.0. There's no real reason it needs to wait until then though. That being said i need to get tests in place for the reporting functionality and they aren't ready yet. I'm working on that, but it may be a couple more days before I get them in place.

I'll update this issue when they are in place and it's ready to release.

**Comment by doesdev** [comment]
Actually, I've done some further thinking on this and I think the best approach would be to see if the maintainers of [rollup-plugin-visualizer](https://github.com/btd/rollup-plugin-visualizer) might want to use this module as the engine for their visualizations. That would allow this module to stay focused on data quality rather than getting into visualizations, an art that I don't have much experience (or particular interest) in. 

You can see #5 for more details, but that is where it stands. I'm going to close this but feel free to join the discussion in the other issue.

**Comment by jharris4** [comment]
ok, thanks for the update! If I really want the analyzer output to go to a file the existing implementation you have will serve as a great guide...

**Comment by jharris4** [comment]
oh, and was about to add that you should remove `htmlReportPath` from `README.md` but I see you were on the ball and have already done so. Thanks for that! ;-)
